# Generated by Django 4.2.3 on 2023-08-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ("-is_done", "-created")},
        ),
        migrations.RenameField(
            model_name="task",
            old_name="performance",
            new_name="is_done",
        ),
        migrations.AlterField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tasks", to="tasks.tag"
            ),
        ),
    ]
